/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.mov

fun main() {
//    print("Hello World!")
//    val nome: String
//    val idade: Int
//
//    nome = "Caio"
//    idade = 10
//
//    val nota = 7.5
//
//    val disciplina: String = "MOV"

    //
//
//    val nome: String?
//    val idade: Int?
//    print("Entre com seu nome: ")
//    nome = readln()
//    println("Entre com sua idade: ")
//    idade = readln().toInt()
//    idade ?: 0
//
//    println("Olá $nome,você tem $idade anos")
//

    val sorteado: Int =(1..10).random()
    var acertou: Boolean = false
    var tentativas = Array(10) { 0 }

    do {
        print("digite um número: ")
        var num = readln().toInt()

        if (sorteado == num){
            print("Você acertou!")
            acertou = true
        }else{
            tentativas[num - 1]++
            println("Tente novamente, você ja tentou $num, ${tentativas[num]} vezes");
            acertou = false
        }

    }while (acertou != true)


}
